### ISSUE TITLE
We receive the below exception when using the styles "bluebook-law-review" and "bluebook2"

### ISSUE THREAD

**Issue by PrimoQA** [michel-kraemer/citeproc-java#100]
Hello Michel, thank you for your help.
We receive the below exception when using the styles "bluebook-law-review" and "bluebook2".
Is it a CSL issue?

java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.util.List (java.lang.Boolean and java.util.List are in module java.base of loader 'bootstrap')
        at de.undercouch.citeproc.CSL.makeBibliography(CSL.java:432)
        at de.undercouch.citeproc.CSL.makeBibliography(CSL.java:412)
        at de.undercouch.citeproc.CSL.makeBibliography(CSL.java:398)
        at de.undercouch.citeproc.CSL.makeAdhocBibliography(CSL.java:624)
        at com.exlibris.primo.webservices.rest.citation.CitationRestApi.generateCslCitation(CitationRestApi.java:208)
        at com.exlibris.primo.webservices.rest.citation.CitationRestApi.citation(CitationRestApi.java:98)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

Thanks.

**Comment by PrimoQA** [comment]
Hello Michel, it is occurring also for the style:  iso690-note-cs.

Thanks.

**Comment by michel-kraemer** [comment]
This issue is fixed in the latest citeproc-java version.
