### ISSUE TITLE
FileSystemNotFoundException when using v. 2.0 in jar

### ISSUE THREAD

**Issue by alaxos** [michel-kraemer/citeproc-java#138]
Hello Michel,

First thanks for providing this library ! We are planning to use it in our spring boot application and I have made the development with version 2.0.0 which seems to be the last stable version. Everything works fine so far when run from my IDE (IntelliJ), but I get an error when I build the application into a jar or a war. When starting the application, I get the following error:

    Caused by: java.nio.file.FileSystemNotFoundException: null
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:169) ~[jdk.zipfs:na]
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:155) ~[jdk.zipfs:na]
	at java.base/java.nio.file.Path.of(Path.java:208) ~[na:na]
	at java.base/java.nio.file.Paths.get(Paths.java:97) ~[na:na]
	at com.oracle.truffle.polyglot.LanguageCache.collectLanguages(LanguageCache.java:355) ~[truffle-api-19.2.1.jar!/:na]
	at com.oracle.truffle.polyglot.LanguageCache.createLanguages(LanguageCache.java:247) ~[truffle-api-19.2.1.jar!/:na]
	at com.oracle.truffle.polyglot.LanguageCache.languages(LanguageCache.java:237) ~[truffle-api-19.2.1.jar!/:na]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.languages(PolyglotEngineImpl.java:578) ~[truffle-api-19.2.1.jar!/:na]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.initializeLanguages(PolyglotEngineImpl.java:526) ~[truffle-api-19.2.1.jar!/:na]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:198) ~[truffle-api-19.2.1.jar!/:na]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:180) ~[truffle-api-19.2.1.jar!/:na]
	at com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:180) ~[truffle-api-19.2.1.jar!/:na]
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:505) ~[graal-sdk-19.2.1.jar!/:na]
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1406) ~[graal-sdk-19.2.1.jar!/:na]
	at de.undercouch.citeproc.script.GraalScriptRunner.<init>(GraalScriptRunner.java:27) ~[citeproc-java-2.0.0.jar!/:na]
	at de.undercouch.citeproc.script.ScriptRunnerFactory.createGraalRunner(ScriptRunnerFactory.java:74) ~[citeproc-java-2.0.0.jar!/:na]
	at de.undercouch.citeproc.script.ScriptRunnerFactory.createRunner(ScriptRunnerFactory.java:91) ~[citeproc-java-2.0.0.jar!/:na]
	at de.undercouch.citeproc.CSL.getRunner(CSL.java:430) ~[citeproc-java-2.0.0.jar!/:na]
	at de.undercouch.citeproc.CSL.<init>(CSL.java:274) ~[citeproc-java-2.0.0.jar!/:na]
	at de.undercouch.citeproc.CSL.<init>(CSL.java:252) ~[citeproc-java-2.0.0.jar!/:na]
	at de.undercouch.citeproc.CSL.<init>(CSL.java:231) ~[citeproc-java-2.0.0.jar!/:na]
	at de.undercouch.citeproc.CSL.<init>(CSL.java:195) ~[citeproc-java-2.0.0.jar!/:na]
    ....

The point seems to be that IJ launches the code with the name of the class and a very large classpath including all libs on disk, but that some classes cannot be found when using the war only, which is how we deploy the application (although all libs seem to be correctly packaged in the war file).

I have just tested with version 3.0.0-alpha.6 and I don't get this error: I can easily start the application from the command line. Any idea how to fix it with v. 2 ? Or is the version 3 close to a release version ?

Thanks for your help,
Nicolas

**Comment by michel-kraemer** [comment]
Please use 3.0.0-alpha.6. It doesn't depend on a JavaScript engine and is also much faster than 2.x. Although it's an alpha version, it should already be very stable - I just wasn't able to find some time yet to release it as a stable version but the plan is to do that soon.

**Comment by alaxos** [comment]
Thanks for your very fast answer ! OK, I'll switch to the version 3. The updates seem very nice, great news !

**Comment by jdsalasca** [comment]
> Please use 3.0.0-alpha.6. It doesn't depend on a JavaScript engine and is also much faster than 2.x. Although it's an alpha version, it should already be very stable - I just wasn't able to find some time yet to release it as a stable version but the plan is to do that soon.

OMG!!!, thank you!!!, you did An amazing work, I was stuck by this problem by 4 hours >.< I'm glad you solve this, Thank you, Thank you, God bless you!
