### ISSUE TITLE
java.lang.NoSuchMethodError: org.mozilla.javascript.ScriptRuntime.getObjectProp

### ISSUE THREAD

**Issue by pcj** [michel-kraemer/citeproc-java#16]
I'm trying to compile the [Getting Started](http://michel-kraemer.github.io/citeproc-java/using/getting-started/) example; I am running into a NoSuchMethodError that I can't seem to overcome.  My code compiles fine through maven with dependencies below.  At runtime, it appears that `citeproc-java/src-gen/main/resources/de/undercouch/citeproc/xmle4x.js` is getting compiled on-the-fly, but it won't run due to mismatch on the method signature with the rhino engine.  AFAIK, this should be loaded in java7 and not present a problem.  Have tried adding in rhino dependencies `org.mozilla:rhino:1.7R4` and `rhino:js:1.7R2` without success.  That's frustrating as the mozilla rhino does seem to have the right method signature.  Any ideas?

### Stacktrace

```
java.lang.NoSuchMethodError: org.mozilla.javascript.ScriptRuntime.getObjectProp(Ljava/lang/Object;Ljava/lang/String;Lorg/mozilla/javascript/Context;Lorg/mozilla/javascript/Scriptable;)Ljava/lang/Object;
	at de.undercouch.citeproc.xmle4x._c_script_0(Unknown Source)
	at de.undercouch.citeproc.xmle4x.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at de.undercouch.citeproc.xmle4x.call(Unknown Source)
	at de.undercouch.citeproc.xmle4x.exec(Unknown Source)
	at de.undercouch.citeproc.script.RhinoScriptRunner.loadScript(RhinoScriptRunner.java:97)
	at de.undercouch.citeproc.CSL.<init>(CSL.java:162)
	at de.undercouch.citeproc.CSL.<init>(CSL.java:130)
	at de.undercouch.citeproc.CSL.<init>(CSL.java:94)
	at de.undercouch.citeproc.CSL.<init>(CSL.java:63)
```

### Example Code
```java
        CSL citeproc = new CSL(new DummyProvider(), "ieee");
        citeproc.setOutputFormat("html");

        citeproc.registerCitationItems("ID-1", "ID-2", "ID-3");

        List<Citation> s1 = citeproc.makeCitation("ID-1");
        System.out.println(s1.get(0).getText());
        //=> [1] (for the "ieee" style)

        List<Citation> s2 = citeproc.makeCitation("ID-2");
        System.out.println(s2.get(0).getText());
        //=> [2]

        Bibliography bibl = citeproc.makeBibliography();
        for (String entry : bibl.getEntries()) {
            System.out.println(entry);
        }
```
### Maven Dependencies

```xml
        <repository>
            <id>oss-snapshots-repo</id>
            <name>Sonatype OSS Maven Repository</name>
            <url>https://oss.sonatype.org/content/groups/public</url>
            <snapshots
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
        </repository>

        <dependency>
            <groupId>de.undercouch</groupId>
            <artifactId>citeproc-java</artifactId>
            <version>0.6</version>
        </dependency>
        <dependency>
            <groupId>org.citationstyles</groupId>
            <artifactId>styles</artifactId>
            <version>1.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.citationstyles</groupId>
            <artifactId>locales</artifactId>
            <version>1.0.1-SNAPSHOT</version>
        </dependency>

```

```sh
$ env | grep JAVA
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home/

$ java -version
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)

$ mvn -v
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T10:37:52-07:00)
Maven home: /usr/local/Cellar/maven/3.2.1/libexec
Java version: 1.7.0_60, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.2", arch: "x86_64", family: "mac"

$ javap -cp  ~/.m2/repository/org/mozilla/rhino/1.7R4/rhino-1.7R4.jar org.mozilla.javascript.ScriptRuntime | grep getObjectProp
  public static java.lang.Object getObjectProp(java.lang.Object, java.lang.String, org.mozilla.javascript.Context);
  public static java.lang.Object getObjectProp(java.lang.Object, java.lang.String, org.mozilla.javascript.Context, org.mozilla.javascript.Scriptable);
  public static java.lang.Object getObjectProp(org.mozilla.javascript.Scriptable, java.lang.String, org.mozilla.javascript.Context);
  public static java.lang.Object getObjectPropNoWarn(java.lang.Object, java.lang.String, org.mozilla.javascript.Context);
```

**Comment by michel-kraemer** [comment]
I'm closing this due to inactivity.
