### ISSUE TITLE
Unable to run citeproc due to script error

### ISSUE THREAD

**Issue by LukaSpehar** [michel-kraemer/citeproc-java#164]
I've created a small test project to see if I can run citeproc without any issues and after providing the .csl file and a locale file, I'm still unable to run it due to what appears to be a script error.

I'm using citeproc-java 2.0.0 from the Maven central repository.
For my data, I used the dummy data given in the "Getting started" example on the citeproc-java website.
I used the ieee.csl style and locale-en-US.xml locale.

This is the stack trace I got:
```
Exception in thread "main" java.lang.IllegalArgumentException: Could not parse arguments
	at de.undercouch.citeproc.CSL.<init>(CSL.java:287)
	at de.undercouch.citeproc.CSL.<init>(CSL.java:252)
	at de.undercouch.citeproc.CSL.<init>(CSL.java:231)
	at de.undercouch.citeproc.CSL.<init>(CSL.java:195)
	at de.undercouch.citeproc.CSL.<init>(CSL.java:164)
	at rs.ac.bg.rcub.Main.main(Main.java:10)
Caused by: de.undercouch.citeproc.script.ScriptRunnerException: Could not call method
	at de.undercouch.citeproc.script.GraalScriptRunner.callMethod(GraalScriptRunner.java:51)
	at de.undercouch.citeproc.CSL.<init>(CSL.java:283)
	... 5 more
Caused by: org.graalvm.polyglot.PolyglotException: TypeError: Cannot read property 'push' of undefined
	at <js>._appendToChildren(Unnamed:2024)
	at <js>.processElement(Unnamed:2053)
	at <js>.CSL.parseXml(Unnamed:2062)
	at <js>.CSL.setupXml(Unnamed:2539)
	at <js>.localeConfigure(Unnamed:9044)
	at <js>.CSL.Engine(Unnamed:3710)
	at <js>.makeCsl(Unnamed:54)
	at org.graalvm.polyglot.Value.execute(Value.java:366)
	at de.undercouch.citeproc.script.GraalScriptRunner.callMethod(GraalScriptRunner.java:49)
	... 6 more

Process finished with exit code 1
```

Below are images of the source code for this test.

![image](https://user-images.githubusercontent.com/39120772/191754437-e9f67339-1044-4461-983c-217fcd584560.png)
![image](https://user-images.githubusercontent.com/39120772/191754491-20f17af4-ed3a-4052-ab00-80442b3c9f0d.png)

**Comment by michel-kraemer** [comment]
Can you try again with the latest version 3.0.0-alpha.6 please? It's much faster, does not depend on GraalJS, and is already quite stable.

**Comment by LukaSpehar** [comment]
Thanks for the very fast response! I managed to get it working with 3.0.0-alpha.6. Cheers!
