### ISSUE TITLE
Cannot process BibEntry with \r

### ISSUE THREAD

**Issue by bartsch-dev** [michel-kraemer/citeproc-java#30]
When one of the BibTeX fields contains a `\r` an exception is thrown.
Maybe this gets fixed when updating jBibTeX?

#### important part of the exception
```
org.jbibtex.TokenMgrError: Lexical error at line 2, column 0.  Encountered: <EOF> after : ""
	at org.jbibtex.LaTeXParserTokenManager.getNextToken(LaTeXParserTokenManager.java:303) ~[jbibtex-1.0.8.jar:?]
	at org.jbibtex.LaTeXParser.jj_ntk(LaTeXParser.java:447) ~[jbibtex-1.0.8.jar:?]
	at org.jbibtex.LaTeXParser.ObjectList(LaTeXParser.java:33) ~[jbibtex-1.0.8.jar:?]
	at org.jbibtex.LaTeXParser.LaTeX(LaTeXParser.java:21) ~[jbibtex-1.0.8.jar:?]
	at org.jbibtex.LaTeXParser.parse(LaTeXParser.java:16) ~[jbibtex-1.0.8.jar:?]
	at de.undercouch.citeproc.bibtex.BibTeXConverter.toItemData(BibTeXConverter.java:161) ~[citeproc-java-0.6.jar:?]
	...
```

**Comment by michel-kraemer** [comment]
Thanks for reporting. You're right - updating jBibTeX seems to have solved this problem. I just uploaded a new snapshot:
https://oss.sonatype.org/content/repositories/snapshots/de/undercouch/citeproc-java/1.0.0-SNAPSHOT/

I hope I can release version 1.0.0 soon.

Michel
