### ISSUE TITLE
citeproc-java requires Java 8 or higher

### ISSUE THREAD

**Issue by ojarabo** [michel-kraemer/citeproc-java#33]
Hi Michel,
First, I would like to appreciate your hard word for creating this great library. 

I would like to include your library into my Android project. However, I am using Java 1.7. I have been reading and trying several solutions to upgrade my project to Java 1.8. Some of them recommend using Jack. However, I am also using Realm as a database for my app. As it is explained [here](
https://github.com/realm/realm-java/issues/2630) and [here](http://stackoverflow.com/questions/36746452/compiling-realm-project-with-jack-compiler) Realm is not working with Jack. 

Is there any possibility to compile citeproc-java with Java 1.7? Any other idea or workaround on how to solve this? I am novel with Java, only a few months, and I am not very agile yet.

Thanks

**Comment by michel-kraemer** [comment]
Hi @ojarabo,

You're right. The latest version of citeproc-java requires Java 8. AFAIK you cannot run Java 8 on Android, but I've never tried it myself. If you want something for Java 7 use the previous version 0.6 of citeproc-java. It should give you equally good results. The javadoc is also still available on the citeproc-java homepage.

I hope this helps. Let me know if you need anything else or if this issue can be closed.

Cheers,
Michel

**Comment by ojarabo** [comment]
Hi @michel-kraemer,
sorry for my late reply. I didn't get any notification of your answer. 
Anyway, I have tried the previous version 0.6. However, when I am instantiating the CSL processor I got the following error:

> FATAL EXCEPTION: main
                  Process: com.example.ojarabo.citationtestjava7, PID: 4366
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.ojarabo.citationtestjava7/com.example.ojarabo.citationtestjava7.MainActivity}: java.lang.RuntimeException: You're using a JRE 6 or lower and Mozilla Rhino was not found in the classpath. The bundled Rhino in JRE 6 does not support E4X (ECMAScript for XML) which is needed for citeproc-java. Either include Rhino in your classpath or upgrade to a newer JRE.
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                   Caused by: java.lang.RuntimeException: You're using a JRE 6 or lower and Mozilla Rhino was not found in the classpath. The bundled Rhino in JRE 6 does not support E4X (ECMAScript for XML) which is needed for citeproc-java. Either include Rhino in your classpath or upgrade to a newer JRE.
                      at de.undercouch.citeproc.script.ScriptRunnerFactory.createJreRunner(ScriptRunnerFactory.java:72)
                      at de.undercouch.citeproc.script.ScriptRunnerFactory.createRunner(ScriptRunnerFactory.java:108)
                      at de.undercouch.citeproc.CSL.<init>(CSL.java:152)
                      at de.undercouch.citeproc.CSL.<init>(CSL.java:130)
                      at de.undercouch.citeproc.CSL.<init>(CSL.java:94)
                      at de.undercouch.citeproc.CSL.<init>(CSL.java:63)
                      at com.example.ojarabo.citationtestjava7.MainActivity.onCreate(MainActivity.java:19)
                      at android.app.Activity.performCreate(Activity.java:6662)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6077) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
Application terminated.

I have been researching for a while, but I have not found any solution on how to include Rhino in my classpath.

Sorry if this is a very basic question, but I am not very proficient in Java. 

Thanks in advance.

**Comment by michel-kraemer** [comment]
It depends on how you're building your app. If you're using a build tool such as Maven or Gradle then look for the instructions here:
http://search.maven.org/#artifactdetails%7Corg.mozilla%7Crhino%7C1.7.7.1%7Cjar

Otherwise download the jar file from the page above and include it in your classpath directly. Let me know if this helps.

**Comment by ojarabo** [comment]
Hi again,
Indeed, that helped to solve the problem. Thank you. 
I am using Gradle, so I included `compile 'org.mozilla:rhino:1.7.7.1'`. However, there was a new error. 

Here you have the trace: 

> FATAL EXCEPTION: main
                                                                                       Process: com.example.ojarabo.citationtestjava7, PID: 19792
                                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.ojarabo.citationtestjava7/com.example.ojarabo.citationtestjava7.MainActivity}: java.lang.UnsupportedOperationException: can't load this type of class file
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                                        Caused by: java.lang.UnsupportedOperationException: can't load this type of class file
                                                                                           at java.lang.ClassLoader.defineClass(ClassLoader.java:594)
                                                                                           at org.mozilla.javascript.DefiningClassLoader.defineClass(DefiningClassLoader.java:27)
                                                                                           at de.undercouch.citeproc.script.RhinoScriptRunner.loadScript(RhinoScriptRunner.java:89)
                                                                                           at de.undercouch.citeproc.CSL.<init>(CSL.java:162)
                                                                                           at de.undercouch.citeproc.CSL.<init>(CSL.java:130)
                                                                                           at de.undercouch.citeproc.CSL.<init>(CSL.java:94)
                                                                                           at de.undercouch.citeproc.CSL.<init>(CSL.java:63)
                                                                                           at com.example.ojarabo.citationtestjava7.MainActivity.onCreate(MainActivity.java:22)
                                                                                           at android.app.Activity.performCreate(Activity.java:6662)
                                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                           at android.os.Looper.loop(Looper.java:154) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

I entered in the debug mode to go throw your code and see where is the problem. There exception is generated in this line `runner.loadScript(getClass().getResource("xmle4x.js"));`. 

Then, I have checked if there was a problem obtaining the URL from `getClass().getResource("xmle4x.js")`. The value returned is `jar:file:/data/app/com.example.ojarabo.citationtestjava7-1/base.apk!/de/undercouch/citeproc/xmle4x.js`. 

I am not really sure whether the URL is incorrect or not. What is clear is that the loadScript is generating the exception. 

I have also checked whether this was a common exception using Rhino and Android. I have found several threads talking about a similar problem. You can find it [here](http://stackoverflow.com/questions/14454686/android-rhino-error-cant-load-this-type-of-class-file). However, I don't know how to apply the provided solutions. 

Do you have any idea on how to solve this, or any work around?
Sorry for the inconveniences and thanks

**Comment by michel-kraemer** [comment]
Interesting. Thanks for the link to the StackOverflow thread. It seems in order to solve the issue you have to modify citeproc-java 0.6 yourself. You have to checkout the 0.6 tag and apply pull request https://github.com/michel-kraemer/citeproc-java/pull/21. This will allow you to set the optimization level as described in the StackOverflow thread.

I'm afraid there is no better solution I can offer you. The major reason for moving to Java 8 was the integrated JavaScript engine Nashorn. Rhino is not maintained anymore and Nashorn is kind of the state-of-the-art solution for JavaScript on the JVM (although there are others of course, but Nashorn is relatively easy to use). Having said that, I'm afraid, I cannot offer support for the old version 0.6 of citeproc-java anymore but I hope you can apply the pull request and compile the library yourself to solve the issue.

**Comment by ojarabo** [comment]
Hi @michel-kraemer,
No problem, I completely understand your reasons and I do thanks you again for your help and support.

I am afraid I will leave it for now and I will wait for a while to see if Google solve the problems with Java 8. Unfortunately, I am an entrepreneur and do not have enough time and resources to dedicate to it at this moment. However, if I find some time I will try to do it so other Android developers can use it. 

I much appreciate your help and all the effort you put to help me to solve the problem and the work you put to create a great library. 

Thanks ;)

**Comment by michel-kraemer** [comment]
No worries. You can get back to me any time. Shall we close the issue then? At least for the time being?

**Comment by ojarabo** [comment]
Yeah sure. 
Thanks
