### ISSUE TITLE
Citeproc-java complains about script related exceptions

### ISSUE THREAD

**Issue by andong777** [michel-kraemer/citeproc-java#34]
Hello, Michel. Very glad to find the useful tool (and the docs) you wrote!

I want to use citeproc-java and CSL to convert some bib files to plain text. I followed the instructions in the documentation on my macbook, but some errors occurred:

>> Exception in thread "main" java.lang.IllegalArgumentException: Could not update items
	at de.undercouch.citeproc.CSL.registerCitationItems(CSL.java:508)
	at de.undercouch.citeproc.bibtex.BibTeXItemDataProvider.registerCitationItems(BibTeXItemDataProvider.java:42)
	at Main.main(Main.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: de.undercouch.citeproc.script.ScriptRunnerException: Could not call method
	at de.undercouch.citeproc.script.JREScriptRunner.callMethod(JREScriptRunner.java:121)
	at de.undercouch.citeproc.CSL.registerCitationItems(CSL.java:506)
	... 7 more
Caused by: javax.script.ScriptException: ReferenceError: "dump" is not defined in <eval> at line number 830
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeMethod(NashornScriptEngine.java:199)
	at de.undercouch.citeproc.script.JREScriptRunner.callMethod(JREScriptRunner.java:117)
	... 8 more
Caused by: <eval>:830 ReferenceError: "dump" is not defined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1441)
	at jdk.nashorn.internal.scripts.Script$Recompilation$288$30224A$\^eval\_.error(<eval>:830)
	at jdk.nashorn.internal.scripts.Script$Recompilation$203$523263A$\^eval\_.dateParseArray(<eval>:12730)
	at jdk.nashorn.internal.scripts.Script$Recompilation$199$100473A$\^eval\_.retrieveItem(<eval>:2870)
	at jdk.nashorn.internal.scripts.Script$Recompilation$198$617052A$\^eval\_.doinserts(<eval>:15103)
	at jdk.nashorn.internal.scripts.Script$Recompilation$195$235101AAAA$\^eval\_.updateItems(<eval>:6064)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:665)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	... 10 more

This is the code I wrote:

```
        BibTeXDatabase db = new BibTeXConverter().loadDatabase(
                new FileInputStream("mybibs.bib"));
        BibTeXItemDataProvider provider = new BibTeXItemDataProvider();
        provider.addDatabase(db);

        CSL citeproc = new CSL(provider, "ieee");
        citeproc.setOutputFormat("text");
        provider.registerCitationItems(citeproc);

        Bibliography bibl = citeproc.makeBibliography();
        for (String entry : bibl.getEntries()) {
            System.out.println(entry);
        }
```

I tried updating the JDK, but nothing changed at all.
I also tried setting it up on a Windows 10 PC, and the errors are almost the same.

Besides, running the citeproc-java interactive shell, produced the same errors:

>> &gt; bibliography
Exception in thread "main" java.lang.IllegalArgumentException: Could not update items
	at de.undercouch.citeproc.CSL.registerCitationItems(CSL.java:508)
	at de.undercouch.citeproc.tool.BibliographyCommand.generateCSL(BibliographyCommand.java:175)
	at de.undercouch.citeproc.tool.BibliographyCommand.doRun(BibliographyCommand.java:137)
	at de.undercouch.citeproc.tool.InputFileCommand.doRun(InputFileCommand.java:121)
	at de.undercouch.citeproc.tool.AbstractCSLToolCommand.run(AbstractCSLToolCommand.java:113)
	at de.undercouch.citeproc.tool.ShellCommand.mainLoop(ShellCommand.java:189)
	at de.undercouch.citeproc.tool.ShellCommand.doRun(ShellCommand.java:110)
	at de.undercouch.citeproc.tool.AbstractCSLToolCommand.run(AbstractCSLToolCommand.java:113)
	at de.undercouch.citeproc.CSLTool.doRun(CSLTool.java:170)
	at de.undercouch.citeproc.tool.AbstractCSLToolCommand.run(AbstractCSLToolCommand.java:113)
	at de.undercouch.citeproc.CSLTool.main(CSLTool.java:132)
Caused by: de.undercouch.citeproc.script.ScriptRunnerException: Could not call method
	at de.undercouch.citeproc.script.V8ScriptRunner.callMethod(V8ScriptRunner.java:146)
	at de.undercouch.citeproc.CSL.registerCitationItems(CSL.java:506)
	... 10 more
Caused by: undefined:830: ReferenceError: dump is not defined
        dump("CSL error: " + str + "\n");
        ^
ReferenceError: dump is not defined
    at Object.CSL.error (<anonymous>:830:9)
    at CSL.Engine.dateParseArray (<anonymous>:12730:25)
    at CSL.Engine.retrieveItem (<anonymous>:2870:48)
    at CSL.Registry.doinserts (<anonymous>:15103:31)
    at CSL.Engine.updateItems (<anonymous>:6064:19)
com.eclipsesource.v8.V8ScriptExecutionException
	at com.eclipsesource.v8.V8._executeVoidFunction(Native Method)
	at com.eclipsesource.v8.V8.executeVoidFunction(V8.java:1004)
	at com.eclipsesource.v8.V8Object.executeVoidFunction(V8Object.java:418)
	at de.undercouch.citeproc.script.V8ScriptRunner.callMethod(V8ScriptRunner.java:144)
	... 11 more

Since I'm not familiar with javascript or the related libraries used in citeproc-java, I'd appreciate if you could help.

**Comment by michel-kraemer** [comment]
The code you wrote looks correct, so I doubt this is the problem. Maybe there is a bug in citeproc-java or in one of the libraries it uses. Have you tried it with a different bibtex file - maybe a small one with only one entry? Please try that and if you can still reproduce the problem send me the file so I can try to reproduce it on my machine too. Thanks.

**Comment by michel-kraemer** [comment]
I just noticed the error happens in `CSL.Engine.dateParseArray`. It seems there is an invalid date in your bibtex file. Can you try to find this entry and post it here or send it to me? Thanks.

**Comment by andong777** [comment]
@michel-kraemer I figured out just now that the problem is due to one bibtex entry in the file. And you are right, removing the month field eliminates the errors.

>> @inproceedings{ICIP99inv,
 author = "M.G. Strintzis and I. Kompatsiaris",
 title = "{3D Model-Based Segmentation of Videoconference Image Sequences}",
 booktitle = "IEEE International Conference on Image Processing '99 (ICIP'99)", 
 address = "Kobe, Japan",
 month = "October 25-28",
 year = "1999", 
 note = {invited paper},
 pages = "",
}

**Comment by michel-kraemer** [comment]
Thanks for the entry. I'll try to debug the issue and get back to you.

**Comment by michel-kraemer** [comment]
@andong777 I just fixed the issue and uploaded a new snapshot:
https://oss.sonatype.org/content/repositories/snapshots/de/undercouch/citeproc-java/1.1.0-SNAPSHOT/

Please try it again with the snapshot and let me know if everything works well. Reopen the issue if it does not.

**Comment by andong777** [comment]
@michel-kraemer It works. :thumbsup: 

Thanks very much for your timely response, Michel.
