### ISSUE TITLE
NPE for the following BibEntry

### ISSUE THREAD

**Issue by Siedlerchr** [michel-kraemer/citeproc-java#82]
Stack trace below
2.1.0-SNAPSHOT
```
@Article{bbbbbbbb,
  author          = {Trapnell, Cole and Pachter, Lior and Salzberg, Steven L.},
  journal         = {2D Materials},
  title           = {{TopHat}: discovering splice junctions with {RNA}-Seq},
  year            = {2009},
  issn            = {1866-0452},
  month           = {mar},
  number          = {9},
  pages           = {1105--1111},
  volume          = {25},
  citation-subset = {IM},
  country         = {Germany},
  created         = {2016-05-06},
  date            = {2016},
  doi             = {10.1093/bbbb/btp120},
  issn-linking    = {1866-0452},
  issue           = {15},
  keywords        = {rank4},
  nlm             = {PMC4860871},
  nlm-id          = {101475967},
  pii             = {arztebl.2016.0261},
  pmc             = {PMC4860871},
  pmid            = {27151464},
  publisher       = {Oxford University Press ({OUP})},
  pubmodel        = {Print},
  pubstatus       = {ppublish},
  revised         = {2016-05-23},
  timestamp       = {2017-07-15},
  url             = {http://www.google.de},
}
```

```
ad] ERROR org.jabref.gui.preview.PreviewViewer - Error while generating citation style
java.lang.NullPointerException: null
        at de.undercouch.citeproc.csl.internal.rendering.SDate.renderInternal(SDate.java:58) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.behavior.Affixes.accept(Affixes.java:38) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.behavior.Affixes.accept(Affixes.java:14) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.behavior.Behavior.lambda$wrap$0(Behavior.java:21) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.rendering.SDate.render(SDate.java:49) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.SRenderingElementContainer.lambda$render$0(SRenderingElementContainer.java:57) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1507) ~[?:?]
        at de.undercouch.citeproc.csl.internal.SRenderingElementContainer.render(SRenderingElementContainer.java:57) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.rendering.SText.renderInternal(SText.java:102) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.behavior.TextCase.accept(TextCase.java:31) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.behavior.TextCase.accept(TextCase.java:17) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.behavior.Behavior.lambda$wrap$0(Behavior.java:21) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.behavior.Quotes.accept(Quotes.java:41) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.behavior.Quotes.accept(Quotes.java:14) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.behavior.Behavior.lambda$wrap$0(Behavior.java:21) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.behavior.Affixes.accept(Affixes.java:38) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.behavior.Affixes.accept(Affixes.java:14) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.behavior.Behavior.lambda$wrap$0(Behavior.java:21) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.rendering.SText.render(SText.java:57) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.SLayout.renderInternal(SLayout.java:43) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.behavior.Affixes.accept(Affixes.java:38) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.behavior.Affixes.accept(Affixes.java:14) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.behavior.Behavior.lambda$wrap$0(Behavior.java:21) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.SLayout.render(SLayout.java:25) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.csl.internal.SBibliography.render(SBibliography.java:66) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.CSL.makeBibliography(CSL.java:1331) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at de.undercouch.citeproc.CSL.makeBibliography(CSL.java:1218) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
        at org.jabref.logic.citationstyle.CSLAdapter.makeBibliography(CSLAdapter.java:56) ~[main/:?]
```

**Comment by michel-kraemer** [comment]
Thanks for reporting. Do you happen to know which style caused the exception?

**Comment by michel-kraemer** [comment]
Never mind. I was able to reproduce it. I'll fix it as soon as possible.

**Comment by michel-kraemer** [comment]
This is fixed now in the latest snapshot.
