### ISSUE TITLE
IndexOutOfBoundsException with empty bibtex entry

### ISSUE THREAD

**Issue by Siedlerchr** [michel-kraemer/citeproc-java#83]
2.1.0-SNAPSHOT
Create a new bibtex entry 
Change CSL Style to Angewandte Chemie International Edition

```
@Book{,
  owner = {Username},
}
```

```
19:19:26.985 [JavaFX Application Thread] ERROR org.jabref.gui.preview.PreviewViewer - Error while generating citation style
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:373) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:425) ~[?:?]
	at de.undercouch.citeproc.csl.internal.format.HtmlFormat.doFormatBibliographyEntry(HtmlFormat.java:37) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
	at de.undercouch.citeproc.csl.internal.format.BaseFormat.formatBibliographyEntry(BaseFormat.java:248) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
	at de.undercouch.citeproc.CSL.makeBibliography(CSL.java:1333) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
	at de.undercouch.citeproc.CSL.makeBibliography(CSL.java:1218) ~[citeproc-java-2.1.0-SNAPSHOT.jar:?]
	at org.jabref.logic.citationstyle.CSLAdapter.makeBibliography(CSLAdapter.java:56) ~[main/:?]
	at org.jabref.logic.citationstyle.CitationStyleGenerator.generateCitations(CitationStyleGenerator.java:56) ~[main/:?]
	at org.jabref.logic.citationstyle.CitationStyleGenerator.generateCitation(CitationStyleGenerator.java:47) ~[main/:?]
	at org.jabref.logic.citationstyle.CitationStylePreviewLayout.generatePreview(CitationStylePreviewLayout.java:15) ~[main/:?]
```

**Comment by michel-kraemer** [comment]
Thanks for reporting. This is fixed now in the latest snapshot.
