### ISSUE TITLE
Problem with bibtex citeKey

### ISSUE THREAD

**Issue by nigermed** [michel-kraemer/citeproc-java#86]
Hi,
I'm working with the citeproc-java 2.0.0.
First I use the library to build the following bibtex item:

`@article{Liliya E. Ziganshina I. Ralph_Edwards 2020, title={In Memoriam}, volume={31}, ISSN={0924-6479}, url={http://doi.org/10.3233/JRS-201002}, DOI={10.3233/JRS-201002}, number={1}, journal={International Journal of Risk & Safety in Medicine}, publisher={IOS Press}, author={Liliya E. Ziganshina and I. Ralph Edwards}, year={2020}, month={Mar}, pages={1–2} }`

Then I try to use that string to create a BibTeXDatabase:
`BibTeXDatabase db = new BibTeXConverter().loadDatabase(new ByteArrayInputStream({string}.getBytes(StandardCharsets.UTF_8)));`
but I get the following error:

`18:22:15.413 [main] ERROR e.c.t.t.BibTexTransformerImpl - exception in converting bibtex
org.jbibtex.ParseException: Encountered unexpected token: "E." <NAME>
    at line 1, column 17.

Was expecting:

    "="

	at org.jbibtex.BibTeXParser.generateParseException(BibTeXParser.java:1164)
	at org.jbibtex.BibTeXParser.jj_consume_token(BibTeXParser.java:1035)
	at org.jbibtex.BibTeXParser.Assignment(BibTeXParser.java:529)
	at org.jbibtex.BibTeXParser.AssignmentList(BibTeXParser.java:537)
	at org.jbibtex.BibTeXParser.Entry(BibTeXParser.java:490)
	at org.jbibtex.BibTeXParser.Object(BibTeXParser.java:293)
	at org.jbibtex.BibTeXParser.Database(BibTeXParser.java:246)
	at org.jbibtex.BibTeXParser.parse(BibTeXParser.java:57)
	at de.undercouch.citeproc.bibtex.BibTeXConverter.loadDatabase(BibTeXConverter.java:135)
	at eu.citation.tool.transformers.BibTexTransformerImpl.transform(BibTexTransformerImpl.java:44)
	at eu.citation.tool.transformers.BibTexTransformerImplTest.test1(BibTexTransformerImplTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)`

I suppose that the library requires a citeKey without spaces, but the citeKey was generated by the library itself.

Could you help me? 
It's a bug or I'm doing something wrong?

Thanks,
Marco

**Comment by michel-kraemer** [comment]
You are right that BibTeX keys must not have spaces. What do you mean with "the citeKey was generated by the library itself"? citeproc-java is not able to create BibTeX items. What library are you referring to?

**Comment by nigermed** [comment]
Hi Michel,
thank you for your answer.
I create a BibTeX item with citeproc-java by using the style "bibtex" taken from org.citationstyles:styles:2.0.0.
CSL citeproc = new CSL(myItemDataProvider,"bibtex","en-US");
citeproc.setOutputFormat("text");
Perhaps the bug is in the "bibtex" style?

**Comment by michel-kraemer** [comment]
> Perhaps the bug is in the "bibtex" style?

Maybe. Maybe not. The style looks OK from what I can see. Can you give me the original CSL citation item you used to generate the BibTeX fragment?

**Comment by nigermed** [comment]
I cannot find anymore the original CSL citation item I used, but try this one:
`{
  "type": "article-journal",
  "journalAbbreviation": "JRS",
  "author": [{
    "family": "Ziganshina",
    "given": "Liliya E."
  }, {
    "family": "Ralph Edwards",
    "given": "I."
  }],
  "issued": {
    "date-parts": [
      [2020, 3, 11]
    ]
  },
  "container-title": "International Journal of Risk & Safety in Medicine",
  "DOI": "10.3233\/JRS-201002",
  "ISSN": "0924-6479",
  "issue": "1",
  "page": "1-2",
  "page-first": "1",
  "publisher": "IOS Press",
  "title": "In Memoriam",
  "URL": "http:\/\/doi.org\/10.3233\/JRS-201002",
  "volume": "31"
}`
the bibtex becomes
`@article{Ziganshina_Ralph Edwards_2020, title={In Memoriam}, volume={31}, ISSN={0924-6479}, url={http://doi.org/10.3233/JRS-201002}, DOI={10.3233/JRS-201002}, number={1}, journal={International Journal of Risk & Safety in Medicine}, publisher={IOS Press}, author={Ziganshina, Liliya E. and Ralph Edwards, I.}, year={2020}, month={Mar}, pages={1–2} }`
where you can see that a space is present between "Ralph" and "Edwards".
The issue occurs everytime a "family" or a "literal" of one (or more) authors contain a space.

**Comment by michel-kraemer** [comment]
OK. I understand where the problem lies.

As you can see here, the citekey is generated by the `author-short` macro, a delimiter `_`, and the `issued-year` macro:
https://github.com/citation-style-language/styles/blob/1ab0241bbf4dc8f3ae8fc7bd5c5b517c9b29cd15/bibtex.csl#L49

The `author-short` macro uses the short form of all author names (typically the family name) and joins them with a delimiter `_`:
https://github.com/citation-style-language/styles/blob/1ab0241bbf4dc8f3ae8fc7bd5c5b517c9b29cd15/bibtex.csl#L57

In your case, the second author's family name is `Ralph Edwards`. In the citation style language, there is no means to replace the white space in this name with the delimiter. That's the reason why you get `Ziganshina_Ralph Edwards_2020` (two family names plus the year joined by a delimiter).

So, IMHO, this is neither a bug in citeproc-java nor in the style. It's just how CSL works (or how it doesn't in this case 😉).

I hope this helps. Let me know if there's anything I can do. Otherwise, please close the issue.

**Comment by nigermed** [comment]
Thank you for the explanation.
My point is: being the "spaces" allowed in the citekey (for the reasons you explained), shouldn't the citeproc-java be enough robust to accept those spaces in the BibTeXConverter().loadDatabase() method without arising the "ParseException"?
