### ISSUE TITLE
`citeproc-java shell` gives a stacktrace on `gnome-terminal`.  No such behaviour with `xterm`

### ISSUE THREAD

**Issue by kjambunathan** [michel-kraemer/citeproc-java#89]
## `citeproc-java shell` gives a stacktrace on `gnome-terminal`.  No such behaviour with `xterm`

Despite the stacktrace, the shell command like `load`, `list` etc works.  So, I believe the stacktrace is harmless.   But it is intimidating for a first time user.

```commit ec76b1c8b341661c19d612f8279ea7b04c99ae9a (HEAD -> master, origin/master, origin/HEAD)
Author: Michel Kraemer <michel.kraemer@igd.fraunhofer.de>
Date:   Sat May 16 22:05:38 2020 +0200

    Fix invalid javadoc


```

### on `gnome-terminal`

```
~/src/citeproc-java$ citeproc-java shell
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
	at jline.UnixTerminal.<init>(UnixTerminal.java:65)
	at jline.UnixTerminal.<init>(UnixTerminal.java:50)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
	at jline.TerminalFactory.create(TerminalFactory.java:102)
	at jline.TerminalFactory.get(TerminalFactory.java:186)
	at jline.TerminalFactory.get(TerminalFactory.java:192)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:243)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:235)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:223)
	at de.undercouch.citeproc.tool.ShellCommand.doRun(ShellCommand.java:65)
	at de.undercouch.citeproc.tool.AbstractCSLToolCommand.run(AbstractCSLToolCommand.java:94)
	at de.undercouch.citeproc.CSLTool.doRun(CSLTool.java:143)
	at de.undercouch.citeproc.tool.AbstractCSLToolCommand.run(AbstractCSLToolCommand.java:94)
	at de.undercouch.citeproc.CSLTool.main(CSLTool.java:105)

Welcome to citeproc-java 2.1.0-SNAPSHOT

Type `help' for a list of commands and `help <command>' for information
on a specific command. Type `quit' to exit citeproc-java.

> 
```

### On `xterm`

```
~/src/citeproc-java$ citeproc-java shell
Welcome to citeproc-java 2.1.0-SNAPSHOT

Type `help' for a list of commands and `help <command>' for information
on a specific command. Type `quit' to exit citeproc-java.

> 

```

**Comment by michel-kraemer** [comment]
Thanks for spotting this. I updated jline to version 3. This should fix the issue. If you like, you can test it again. Let me know if the problem persists.
